server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: lax

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: training-app
            client-secret: 0vUVSqXwQbKiCCfUQjhicVMu2naNi5wf
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/training
            authorization-uri: http://localhost:8180/realms/training/protocol/openid-connect/auth
            token-uri: http://localhost:8180/realms/training/protocol/openid-connect/token
            user-info-uri: http://localhost:8180/realms/training/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8180/realms/training/protocol/openid-connect/certs
            user-name-attribute: preferred_username

# Backend API Configuration
backend:
  url: http://localhost:8081
  
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
